workflows:
  android-workflow:
    name: Android Debug APK
    instance_type: mac_mini_m1
    working_directory: build-android-start
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/build-android-start/local.properties"
      - name: Build APK
        script: ./gradlew assembleDebug
      - name: List APK files
        script: find . -name "*.apk"
    artifacts:
      - build-android-start/**/*.apk
    publishing:
      email:
        recipients:
          - kutschmann.s@web.de
